FROM etherpad/etherpad:1.8.7


# ENV DB_HOST = ENTER YOUR DB_HOST HERE
# ENV DB_PORT = ENTER YOUR DB_PORT HERE
# ENV DB_DATABASE = ENTER YOUR DB_DATABASE HERE
# ENV DB_USER = ENTER YOUR DB_USER HERE
# ENV DB_PWD = ENTER YOUR DB_PWD HERE

COPY ./settings.json /opt/etherpad-lite/settings.json
COPY ./ProjectHubSkin /opt/etherpad-lite/src/static/skins/ProjectHubSkin