apiVersion: v1
kind: Namespace
metadata:
  name: project-hub
  labels:
    ref: project-hub
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: project-hub
  labels:
    ref: project-hub
data:
  db_host: "db"
  db_port: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-secret
  namespace: project-hub
  labels:
    ref: project-hub
data:
  db_name: "project_hub"
  db_pwd: "P@ssw0rd"
  db_user: "project-hub-db-user"
  db_rootpwd: "P@ssw0rd"