apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: project-hub
  labels:
    app: project-hub
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/project-hub/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: project-hub
  labels:
    app: project-hub
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project-hub
  labels:
    ref: project-hub
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: project-hub
  labels:
    ref: project-hub
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        ref: project-hub
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: db_rootpwd
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: db_pwd
        ports:
        - containerPort: 3306
          name: mysql
      #   volumeMounts:
      #   - name: k8s-mysql-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: k8s-mysql-storage
      #   emptyDir: {}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim